import { DefaultTheme } from 'styled-components';

export const theme: DefaultTheme = {
  BAR_STYLE: 'dark-content',
  BAR_BACKGROUND_COLOR: 'transparent',
  INITIAL_BORDER: 24,
  FONT_SIZE_H1: '28px',
  FONT_SIZE_H2: '24px',
  FONT_SIZE_H3: '18px',
  FONT_SIZE_H4: '14px',
  FONT_SIZE_H5: '12px',
  FONT_SIZE_H6: '10px',
  FONT_SIZE_H1_MOB: '28px',
  FONT_SIZE_H2_MOB: '24px',
  FONT_SIZE_H3_MOB: '18px',
  FONT_SIZE_H4_MOB: '14px',
  FONT_SIZE_H5_MOB: '12px',
  FONT_SIZE_H6_MOB: '10px',
  FONT_FAMILY: 'LeagueSpartan',
  FONT_FAMILY_BOLD: 'LeagueSpartan-Bold',
  BACKGROUND_COLOR: '#e5ddc8',
  PRIMARY_COLOR: '#4a4a4a',
  BORDER_COLOR: '#dfe0e2',
  ALERT_COLOR: '#db1f48',
  LIGHT_COLOR: '#fff',
  PALLETE01_COLOR: '#e5ddc8',
  PALLETE02_COLOR: '#01949a',
  PALLETE03_COLOR: '#004369',
  PALLETE04_COLOR: '#db1f48',
  GRAY_COLOR: '#dfe0e2'
};
