name: CI

on:
  push:
    branches: [ develop ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Develop
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
      
      - name: Install Dependencies
        run: yarn
        
      - name: build
        run: yarn build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_PROJECT: ${{ secrets.REACT_APP_PROJECT }}
          REACT_APP_VERSION: ${{ secrets.REACT_APP_VERSION }}
          REACT_APP_PROJECT: ${{ secrets.REACT_APP_PROJECT }}
          REACT_APP_CONTACT: ${{ secrets.REACT_APP_CONTACT }}
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.QA_SSH_HOST }}
          username: ${{ secrets.QA_SSH_USER }}
          port: ${{ secrets.QA_SSH_PORT }}
          key: ${{ secrets.QA_SSH_KEY }}
          passphrase: ${{ secrets.QA_SSH_PASSPHRASE }}
          source: "., !node_modules"
          target: "/var/www/html/memorizou/web"
          